docs/Splashkit/Applications/Meeting Minutes/ReadMe

Meeting Minutes

---

docs/Splashkit/Applications/Meeting Minutes/MM11April.md

Meeting Minutes April 11th

---

docs/Splashkit/Applications/Meeting Minutes/MM14April.md

meeting minutes for the 14th

---

.github/pull_request_template.md
.github/workflows/ci.yml
README.md

Adding workflow files and pull request template

ADD: copy workflow

---

docs/OnTrack/Jupyter Notebook/Prototype SRS (Software Requirements Specification).md

Pull Request to upload Jupyter Notebook SRS Document to company files.
Nil
N/A
N/A
N/A

docs: Upload Jupyter Notebook SRS Document .md file

---

docs/OnTrack/Jupyter Notebook/Meeting Minutes/22.4.22.md

Pull Request to upload Jupyter Notebook Meeting Minutes file for 22.4.22
Nil
N/A
N/A
N/A

docs: Upload Jupyter Notebook Meeting Mins file 22.4.22

---

docs/OnTrack/Jupyter Notebook/Meeting Minutes/18.4.22.md

Pull Request to upload Jupyter Notebook Meeting Mins file for 18.4.22
Nil
N/A
N/A
N/A

docs: Upload Jupyter Meeting Mins file 18.4.22

---

docs/OnTrack/Jupyter Notebook/Meeting Minutes/14.4.22.md

Pull Request to upload Jupyter Notebook Meeting Mins file for 14.4.22
Nil
N/A
N/A
N/A

docs: Upload Jupyter Meeting Mins 14.4.22

---

docs/OnTrack/Jupyter Notebook/Meeting Minutes/11.4.22.md

Pull Request to upload Jupyter Notebook Meeting Mins file for 11.4.22
Nil
N/A
N/A
N/A

docs: Upload Jupyter Meeting Mins file 11.4.22

---

docs/OnTrack/Jupyter Notebook/Meeting Minutes/4.4.22.md

Pull Request to upload Jupyter Notebook Meeting Minutes file for 4.4.22
Nil
N/A
N/A
N/A

docs: Upload Jupyter Notebook Meeting Mins file 4.4.22

---

docs/OnTrack/Jupyter Notebook/Meeting Minutes/28.3.22.md

Pull Request to upload Meeting Minutes file for Jupyter Notebook Meeting 28.3.22
Nil
N/A
N/A
N/A

docs: Upload J Notebook Meeting Mins 28.3.22

---

README.md

Documentation ReadMe update
Fixes # No issues but just fixes to the contents

UPDATE: README page description

---

docs/OnTrack/Jupyter Notebook/Meeting Minutes/23.3.22.md

Pull Request to upload Jupyter Notebook meeting minutes for 23.3.22
Nil
N/A
N/A
N/A

docs: Add J Notebook Meeting Mins: 23.3.22

---

docs/OnTrack/Deployment/Meeting minutes/week 4

week 4 Meeting minutes

---

docs/OnTrack/Jupyter Notebook/Jupyter-Notebook-Epic-T1-2022.md

Pull Request to add Jupyter Notebook Team Epic to company files.
Nil
N/A
N/A
N/A

docs: Upload Jupyter Notebook Epic

---

docs/OnTrack/Jupyter Notebook/Meeting Minutes/25.4.22.md

Pull Request to upload Jupyter Notebook Meeting Mins for 25.4.22
Nil
N/A
N/A
N/A

docs: Upload Jupyter Notebook Meeting Mins file 25.4.22

---

docs/OnTrack/Front End Migration/Testing Decision Process.md

Front-End Migration Testing Decision Process
This is the Front-End Migration Testing Decision Process MD document written by Ishrat Jahan.

Added md file via upload

---

docs/OnTrack/Jupyter Notebook/Index.md
docs/OnTrack/Jupyter Notebook/Meeting Minutes/11.4.22.md
docs/OnTrack/Jupyter Notebook/Meeting Minutes/14.4.22.md
docs/OnTrack/Jupyter Notebook/Meeting Minutes/18.4.22.md
docs/OnTrack/Jupyter Notebook/Meeting Minutes/22.4.22.md
docs/OnTrack/Jupyter Notebook/Meeting Minutes/28.3.22.md
docs/OnTrack/Jupyter Notebook/Meeting Minutes/4.4.22.md
docs/OnTrack/Jupyter Notebook/Prototype SRS (Software Requirements Specification).md

Added navigation links so that it is easier to use the documentation

update navigation for jupyter notebook documentation

---

docs/OnTrack/Voice Verification/Voice Verification SRS Document.md

Change SRS document (docx) to .md file and upload to company documentation repo

docs: Upload Voice Verification SRS Document (Ver 1.0)

---

docs/OnTrack/Deployment/Deployment Epic

this is the final version of the epic, used for the deployment team
documentation
expected)

Deployment Epic

---

docs/Splashkit/Operations/Distribution Channels/Index.md

This PR adds a first draft of the overview documentation for the SplashKit Operations Team

docs: Add draft overview for operations team.

---

docs/OnTrack/Jupyter Notebook/Meeting Minutes/2.5.22.md

Pull Request to add Jupyter Notebook Meeting Minutes file for 2.5.22
Nil
N/A
N/A
N/A

docs: Add Jupyter Notebook Meeting Mins for 2.5.22

---

docs/OnTrack/Front End Migration/Research & Findings/Testing Decision.md
docs/OnTrack/Front End Migration/Research & Findings/revise_prosconsofdifferentframeworks.md

This file compares different framework and we are discussing two levels of testing in this issue. For unit testing and end to end testing.
In this issue, we will discuss the current state of testing and what tools are we proposing and why we think it is logical to choose that over others. We will discuss some alternative tools and their pros and cons as well which we considered in our decision-making process.

Elabortating our framework choice and it's future 

---

docs/Splashkit/Extensions/Language Extensions/Research & Findings/Software Change Request Form

For review by Thoth-tech management for semester 2.
This request is for a software change request form to be reviewed by the appropriate parties. In our investigation of translator issues, it was determined that the documentation generator in use is outdated and incompatible with the Windows platform. Additional troubleshooting was required every step of the way and alternative solutions are updated regularly, provide greater compatibility, and might resolve the primary issue the team was seeking to identify and resolve.

Software Change Request Form for Translator

---

docs/Splashkit/Extensions/Language Extensions/Research & Findings/Software Change Request Form.md

Final update to formatting

---

docs/Splashkit/Extensions/Python Compatibality/Research & Findings/Python 3.8 Changelog.md

Began a changelog for Python 3.8 to aid in tracking down the incompatibility issue.

Python 3.8 changelog (incomplete)

---

docs/Splashkit/Applications/Meeting Minutes/mm5May.md

Add  minutes

---

docs/OnTrack/Deployment/Enhanced Authentication/current-and-proposed-authentication-evaluation-5.1.md

Create document evaluating current and proposed OnTrack authentication
This documentation has been created to evaluate and compare the current state of the OnTrack authentication system and the proposed authentication solutions to be developed by the Enhance Authentication team.

docs: create authentication evaluation

---

docs/OnTrack/Deployment/Software Requirements Specifications Document

Due to the previous SRS that the deployment team made not being up to standard, I've made the necessary changes to the documentation, and now includes all the correct material 
I've tested the documentation in both Firefox and Chrome, and the documentation works as intended on both platforms. Later I will do testing on Safari to ensure that the documentation is working on all platforms

Software Requirements Specifications Document

---

docs/OnTrack/Deployment/User Stories

User stories document, which can also be found on teams Trello board
Documentation
expected)

Create User Stories

---

docs/Splashkit/Extensions/Language Extensions/Research & Findings/Software Change Request.md

Attempting to add new documentation following updated formatting.

Create Software Change Request.md

---

docs/Splashkit/Extensions/Python Compatibality/Research & Findings/Python Changelog.md

Trying to get the python changelog past the prettier check. Removed code blocks temporarily.

Create Python Changelog.md

---

docs/OnTrack/Jupyter Notebook/Meeting Minutes/16.5.22.md

Pull Request to add Jupyter Notebook Meeting Minutes file for 16.5.22
Nil
N/A
N/A
N/A

docs: Add Jupyter Notebook Meeting Mins 16.5.22

---

docs/Splashkit/Operations/Distribution Channels/testing/test-strategy.md

This PR includes first draft of testing strategy document based on the Thot Tech documentation template.
expected)
Proof read and formatted with prettier.

docs: Add first draft of testing strategy for SplashKit distribution channels

---

README.md

Fix small typos and tweak wordings on README.

docs: fix typos on README

---

docs/OnTrack/Jupyter Notebook/Meeting Minutes/20.5.22.md

Pull Request to upload Jupyter Notebook Meeting Minutes file for 20.5.22
Nil
N/A
N/A
N/A

docs: Upload Jupyter Notebook Meeting Minutes for 20.5.22

---

docs/DreamBig/Sprint 2 documentation/Figma Tool Demo.md

Create Figma Tool Demo.md

---

docs/Splashkit/Modules/Physics/Software_Requirements_Specification.md

Purpose, intended audience, intended use, scope and definitions added.
Adding detail to the Physics SRS document.
- [ x ] Documentation (update or new)
Have ran the Prettier and Vale checks.
- [ N/A ] Tested in latest Chrome
- [ N/A ] Tested in latest Safari
- [ N/A ] Tested in latest Firefox
- [ Y ] My code follows the style guidelines of this project
- [ Y ] I have performed a self-review of my own code
- [ Y ] I have commented my code in hard-to-understand areas
- [ Y ] I have made corresponding changes to the documentation
- [ Y ] My changes generate no new warnings
- [ Y ] I have requested a review from ... on the Pull Request

docs: Add introduction to physics srs document

---

docs/Splashkit/Modules/Data Analytics/Research & Findings/Data_Frame_Redesign_2022_Trimester_2.md

Added research and findings from a review and redesign of dataframes
This change adds documentation about the research and findings that took place to review and redesign the dataframe code.
Prettier tests have been run.

docs: add dataframe redesign research

---

docs/Internal Systems/SRS.md

SRS for Documentation Infrastructure System

Added SRS document

---

docs/Splashkit/Applications/Meeting Minutes/MM_GameTeam_22ndAugust.md
docs/Splashkit/Applications/Meeting Minutes/MM_GameTeam_25thJuly.md
docs/Splashkit/Applications/Meeting Minutes/MM_GameTeam_30thJuly.md
docs/Splashkit/Applications/Meeting Minutes/MM_GameTeam_3rdSeptember.md
docs/Splashkit/Applications/Meeting Minutes/MM_GameTeam_4thAugust.md
docs/Splashkit/Applications/Meeting Minutes/MM_GameTeam_6thAugust.md
docs/Splashkit/Applications/Meeting Minutes/MM_GameTeam_8thAugust.md
docs/Splashkit/Applications/Meeting Minutes/MM_GameTeam_8thSeptember.md

Converted all the Build a Game Team's meeting minutes into markdown format using prettier.
Been tested on Firefox, Chrome and Safari and using vs code

Moved all the meeting minutes into a markdown format

---

docs/OnTrack/Documentation/OnTrack Documentation Template.md

Pull Request for OnTrack Documentation Template
N/A
N/A
N/A

docs: Upload OnTrack Documentation Template

---

docs/Splashkit/Modules/Physics/Background/Software_Requirements_Specification.md

Update includes "user needs" and "assumptions and dependencies"
Missing documentation for the Physics module has been added to give context to the module
- [ x ] Documentation (update or new)
Lint checks and formatting was undertaken on the file
- [ x ] Tested in latest Chrome
- [ x ] Tested in latest Safari
- [ x ] Tested in latest Firefox
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] I have requested a review from ... on the Pull Request

docs: Physics srs overall description added

---

docs/.vale/thothtech/spelling-exceptions.txt
docs/Splashkit/Modules/Machine Learning/Feature List.md

Added feature list to aid in handover
ran prettier/vale

add: feature list

---

docs/OnTrack/Voice Verification/Handbook for Voice Verification.md

Update: update Voice Verification Handbook

---

Dicey Combat.md
docs/ArtGallery/DockerizationFeasabilityCheck.md
docs/ArtGallery/DockerizationProjectOutline.md
docs/Internal Systems/Research & Findings/Google-github-actions.md
docs/Internal Systems/Research & Findings/gatsby/gatsby.md
docs/OnTrack/Documentation/architecture-doc.md
docs/OnTrack/Voice Verification/Architecture-Document.md
docs/Splashkit/Applications/Build a COOL game/DiceyCombat/diceycombat.cpp

Providing the project outline and feasibility check for the dockerization of the indigenous art gallery project.
New documentation

doc: dockerization project outline and feasability check

---

docs/Templates/Project-Templates/Component-Review.md

This is an updated template document for Component Reviews. With more detail around adding screenshots and checklists.
Tested by auto test in GitHub for formatting.

docs: Added Component Review Template

---

docs/ArtGallery/Lighthouse Project/Project Report

Lighthouse Project Report

---

docs/.vale/thothtech/Admin.yml
docs/.vale/thothtech/CodeblockFences.yml
docs/.vale/thothtech/CurrentStatus.yml
docs/.vale/thothtech/FirstPerson.yml
docs/.vale/thothtech/ReadingLevel.yml
docs/.vale/thothtech/Uppercase.yml
docs/OnTrack/Data Analytics Platform/T1_2023/DataPoint-research-documentation.md
docs/Splashkit/Modules/Machine Learning/Research & Findings/VS Code/launch.json
docs/Splashkit/Modules/Machine Learning/Research & Findings/VS Code/settings.json
docs/Splashkit/Modules/Machine Learning/Research & Findings/VS Code/tasks.json

OnTrack-DataAnalyticsproject
This is initial Documentation KickOff for OnTrACK DATA ANALYTICS PLATFORM, on comencement of feedback and survey we plan to expand this and have intial design and analysis included here.
needs work on requirement setup 
Add Documentation
Prettier

This is documenation for requirements in T1-2023, for OnTrack-DataAnalyticsproject

---

docs/OnTrack/Numbas/ProjectSignOffNumbas.md

Changed the Image links and headers to be correct. Daniel Maddern
This is an updated to existing documentation. The links for the images were not working. I have adjusted these and some of the headers.

docs:fixed errors with images in numbas doc

---

docs/ArtGallery/Dockerization/DockerizationResearchNotes.md

fixing up and adding to Docker research notes

doc: tidy research notes on Docker

---

docs/ArtGallery/Lighthouse Project/SEOResearch.md

Added SEO research md doc as part of front end optimisation for Art Gallery - relating to the objective of the lighthouse project to identify other testing tools. 
added vale and prettier extensions to vs code, used command pallet to run format document

added SEO research doc

---

docs/ArtGallery/Documentation Project/DocumentationProgressReportWeek5.md

Added the missing content to the week 5 progress report, which was accidently unsaved and missing from the document.

docs: fixed issue of week 5 report being blank

---

docs/ArtGallery/Dockerization/DockerizationResearchNotes.md

update: docker documentation

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Assessments_api.rb .md
package-lock.json

Documentation explaining how assessments API file functions
This is documentation explaining the function of the DreamBig API file: assessments_api.rb
Should there be any possible bug or error found it will be noted within the document.
I am unsure, I am writing documentation of the existing API code for the DreamBig project. This is made in MarkDown format.

docs:dreambig_API doc assessments.md

---

docs/ArtGallery/Documentation Project/DocumentationResearchNotes.md

Added further hosting and BookStack research to site.

docs: added more to research document

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Avatar_accessories_api.rb.md

This is documentation of the API file Avatar_accessories explaining its functions and related API files.
JadenDMD@GMail.com
This is documentation of the API file Avatar_accessories, its functions and its related API files.
- [ X] Documentation (update or new)
This is documentation hence it does not require testing.

docs:Documentation of Avatar_accessory

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Avatar_api.rb.md

This is documentation of the API file Avatar, its function and its related API files.
This is documentation of the API file AVatar, its function and its related API files.
This is documentation of API files, no testing is required.

docs:Documentation of AvatarAPI

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Avatar_heads_api.rb.md

Documentation of API file avatar_heads, its functions, related API files and related frontend services.
JadenDMD@GMail.com
Documentation of API file avatar_heads
This is documentation, so no testing is required.

docs:Avatar_heads API Documentation

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Avatar_torsos_api.rb.md

This is documentation of API file avatar_torso, its functions, related API files and frontend services.
Documentation of API file Avatar_torsos
- [ X] Documentation (update or new)
This is documentation, so no testing is required

docs:Avatar_torso API file documentation

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Category_api.rb.md

This is documentation of category file, related API files and frontend services.
Documentation of API file 'category'
- [ X] Documentation (update or new)

docs:Category_API Documentation

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Category_questions_api.rb.md

This is documentation of API file Category_questions, related API files and frontend services.
JadenDMD@GMail.com
This is documentation of the API file Category_questions

docs:Documentation of API file Category_questions

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Journeys_api.rb.md

This is documentation of the API file Journeys, its related API files and frontend services.
This is documentation of API file Journeys.
- [ X] Documentation (update or new)

docs:Documentation of API file Journeys

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Users_api.rb.md

This is documentation of the API file Users, related API files and frontend services.
Jaden
This is documentation of the API file Users.

docs:Documentation of API file Users

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Teachers_api.rb.md

Documentation of empty file Teachers. This needs to be implemented for future use with other API files.
Jaden
Documentation of empty file Teachers.

docs:Documentation of API files Teachers

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Student_api.rb.md

This is documentation of the API file Student, its related API files and frontend services.
Jaden
This is documentation of the API file Student.
This is documentation of the API file Student.

docs:Documentation of API file Student

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Sections_api.rb.md

This is documentation of the API file Sections, its related API files and frontend services.
Jaden
This is documentation of the API file Sections.
This is documentation, so no testing is required.

docs:Documentation of API file Sections

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Role_api.rb.md

Empty API file. Needs to be implemented for future use.
Jaden
Documentation of empty API file for Role_API.
This is documentation, so no testing is required.

docs:Documentation of Role_API

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Reflections_api.rb.md

This is documentation of the API file Reflections, its related API files and frontend services.
Jaden
This is documentation of the API file Reflections.

docs:Documentation of API file Reflections

---

docs/DreamBig/Documentation & QA/2023_T1_API/DreamBig Markdown Plans_api.rb.md

This is documentation of the API file Plans, its related API files and frontend services
Jaden
Documentation of API file Plans.

docs:Documentation of API file Plans

---

docs/DreamBig/Documentation & QA/2023_T1_UX/UX-Testing-Report.md
docs/DreamBig/UX Testing T1-2023/Deliverables.md

chore: fix linting errors

---

docs/ArtGallery/Deployment/DeploymentStrategies.md

docs: fixing prettier errors in Ayan's commit

---

docs/Splashkit/Applications/Tutorials and Research/Tutorial Proposals/Getting Started in Splashkit Outline.md

The tutorial proposal / outline for the Getting Started With Splashkit tutorial(s), highlights basic function usage, purpose of the tutorial(s) and structure.
- [✓ ] New feature (non-breaking change which adds functionality)
expected)
- [ ✓] Documentation (update or new)
The tutorial content has been tested by running the linters / formatters as detailed in the contribution guide, as well as being only intended for internal tutorial planning purposes only.
- [ ✓ ] Tested in latest Firefox
- [ ✓ ] My code follows the style guidelines of this project
- [  ✓] I have performed a self-review of my own code
- [  ✓] I have commented my code in hard-to-understand areas
- [  ✓] I have made corresponding changes to the documentation
- [  ✓] My changes generate no new warnings
- [  ✓] I have …

Getting Started With Splashkit - Windows Tutorial Proposal

---

docs/Splashkit/Applications/Tutorials and Research/Tutorial Proposals/Splash World Adventures.md

The pull request includes the submission of the "Software Requirements Specification for Mario-Like Game Tutorial Using Splashkit" document, which outlines the purpose, features, user case, class diagram, and sequence diagrams for the game and tutorial.
Formatted using linters with repository config.

add SRS for Mario-like game for tutorials

---

docs/Splashkit/Applications/Tutorials and Research/Tutorial Proposals/Building the SplashKit Core Library with CMake.md

This pull request proposes a tutorial for understanding the CMakeLists.txt file used in building the SplashKit core library. The tutorial aims to help Splashkit developers effectively compile and link the library on various platforms for game development and multimedia projects.
The tutorial proposal has been reviewed and tested with Prettier and Vale s to ensure its adherance to policy.
_N/A_

Cmake tutorial

---

docs/Splashkit/Applications/Tutorials and Research/Tutorial Proposals/Getting Started With Sprite Layering In Splashkit - C#.md
docs/Splashkit/Applications/Tutorials and Research/Tutorial Proposals/Getting Started With Sprites in Splashkit Outline - C#.md

The tutorial proposal / outline for the base Sprite positioning tutorial (also acting as a Getting Started With Sprites tutorial) as well as a document for the Sprite Layering proposal
- [✓ ] New feature (non-breaking change which adds functionality)
expected)
- [ ✓] Documentation (update or new)
The tutorial content has been tested by running the linters / formatters as detailed in the contribution guide, as well as being only intended for internal tutorial planning purposes only.
N/a
- [ ✓ ] My code follows the style guidelines of this project
- [  ✓] I have performed a self-review of my own code
- [  ✓] I have commented my code in hard-to-understand areas
- [  ✓] I have made corresponding changes to the documentation
- [  ✓] My changes generate no new warnings
- [  ✓] I have requested …

Added Getting Started  With Sprites / Sprite Layering

---

docs/Splashkit/Applications/Tutorials and Research/Tutorial Proposals/Understanding SplashKit Manager (SKM) Shell Commands.md

This pull request adds a tutorial proposal titled "Understanding SplashKit Manager (SKM) Shell Commands" to the main repository. The tutorial aims to provide a comprehensive understanding of each SKM shell command used in managing SplashKit projects. It covers the usage, examples, and common use cases for each command, targeting intermediate-level programmers interested in game development with the SplashKit library.
The proposed tutorial has been tested by linting with Prettier and Vale using the respective rc files.

add skm shell command tutorial proposal

---

docs/OnTrack/Staff Grant Extension/REQUIREMENTS.md

Requirements documentation for the new feature "Staff Grant Extension".

docs: staff grant extension requirements documentation

---

docs/ArtGallery/BackendUpgrades/AsynchronyProposal.md

doc: proposal on implementing asynchrony in the art gallery API

---

docs/Splashkit/Applications/Tutorials and Research/Tutorial Proposals/Introduction to Key Codes.md

Tutorial Proposal for the Key Code data type in markdown. No dependencies.
Checked preview of markdown file on VS Code.

Key Codes Tutorial Proposal

---

docs/Splashkit/Applications/Tutorials and Research/Tutorial Proposals/Getting Started With Mouse Button and Inputs.md

Tutorial proposal for Mouse Button for the SplashKit project
Tested as a preview on VS Code. Checked with Prettier.

Mouse Button tutorial proposal

---

docs/Splashkit/Applications/Arcade Machines/Research & Findings/Asteroids Game Test Report

Create Asteroids Game Test Report

---

Starlight-Documentation-Website/src/content/docs/products/ontrack/documentation/front-end-migration/deploy-ontrack-using-docker/docker-compose-with-wsl2.md

test netlify issue

---

docs/Splashkit/Applications/Tutorials and Research/Tutorial Proposals/Tutorial Markdowns/Getting Started With Mouse Button and Inputs.md
docs/Splashkit/Applications/Tutorials and Research/Tutorial Proposals/Tutorial Markdowns/Introduction to Key Codes.md

A markdown tutorial for the SplashKit key codes.
Ran through prettier and tested as preview on VS Code.

SplashKit tutorial - Key Codes and Mouse Buttons

---

docs/Splashkit/Applications/Tutorials and Research/Tutorial Proposals/Getting Started With SplashKit Database.md

A markdown file tutorial proposal for SplashKit Database
Tested as preview on VS Code and run on prettier.

Tutorial Proposal - SplashKit Database

---

docs/ConvertTrello.py

This is a python script for converting Trello JSON in to CSV format.
expected)

ConvertTrello.py

---

docs/ArtGallery/2023T2-handover.md

add: handover for Art Gallery

---

docs/OnTrack/Documentation/Spike-Frontend-Documentation-Investigation.md

Added spike frontend documentation investigations document.

add spike frontend documentation investigations

---

Arcade Games Bugs and Improvements/Arcade Game Bug Testing Spike Plan.md
Arcade Games Bugs and Improvements/Bugs/Car-Race/Car Race Clipping Bug.md
Arcade Games Bugs and Improvements/Bugs/DXBallGame/DXBallGame Controls Bug.md
Arcade Games Bugs and Improvements/Bugs/Pingpong/PingPong Playspace Collision Bug.md
Arcade Games Bugs and Improvements/Bugs/Pingpong/Pingpong Paddle Collisions Bug.md
Arcade Games Bugs and Improvements/Improvement Suggestions/Below The Surface/Below The Surface Enemy Recolour.md
Arcade Games Bugs and Improvements/Improvement Suggestions/Runner Dash/Runner Dash Enemy Movement Changes.md
Arcade Games Bugs and Improvements/Improvement Suggestions/Venture Adventure/Venture Adventure Restart Level Option.md
docs/.vale/thothtech/MeaningfulLinkWords.yml
docs/OnTrack/Feedback Enhancement/tutor feedback enhancement feature.md

Adds documentation for tutor feedback enhancement feature in OnTrack.
Formatted and tested using `prettier` and `vale` in accordance with
contribution guidelines.
Documentation only. No code changes.
~- [ ] Tested in latest Chrome~
~- [ ] Tested in latest Safari~
~- [ ] Tested in latest Firefox~

docs: add documentation for tutor feedback enhancement

---

docs/Splashkit/Extensions/DebianDebPackaging.md

https://trello.com/c/wXo9Dny0/432-create-debian-package-for-splashkit Have been unable to implement requested functionality, this documents the work done so far.
Tested locally in  VS Code markup preview as well as by previewing file in GitHub.

Tech spike for Debian packaging

---

docs/OnTrack/UI Enhancement/Component Reviews/group-selector.md

Migration of group-selector component
expected)

Component review

---

docs/Splashkit/Tutorials/Reviews/Introduction to JSON in SplashKit-Tutorial Review Document.md

Review documentation for tutorials on the Splashkit website.
The Introduction to JSON in SplashKit tutorial is checked and the code is all right.
It works properly, making sure that all C# code is top-level, and making minor changes to the text to make the content more coherent. This document covers all the checks and links to the PR for this audit.

review Introduction to JSON in SplashKit

---

docs/Splashkit/Tutorials/Reviews/getting-started-with-servers.md

Document for the review of a tutorial on the Splashkit Site.
The tutorial **Getting Started with Servers** was reviewed and updated to ensure all code runs correctly and uses top level statements. The document covers all checks made and links to the PR made for this review.

Getting Started With Servers - Tutorial Review Document

---

docs/Splashkit/Tutorials/Reviews/routing-with-servers.md

Document for the review of a tutorial on the Splashkit Site.
The tutorial **Routing with Servers** was reviewed and updated to ensure all code runs correctly and uses top level statements. The document covers all checks made and links to the PR made for this review.

Routing With Servers - Tutorial Review Document
